# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-27 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailinventory', '0001_initial'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailpages', '0062_merge_20190325_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peoplepage',
            name='primarypage_ptr',
        ),
        migrations.DeleteModel(
            name='PeoplePage',
        ),
    ]
